### ISSUE TITLE
It's not properly forked.

### ISSUE THREAD

**Issue by ashwini0529** [GDGVIT/AOSP-fork#1]
The point of creating this issue was the repository name which seems misguiding in finding out where the actual repository is. If it was a mirror, it could have been named a mirror.

**Comment by SphericalKat** [comment]
I know what a fork is, thank you. This repository wasn't named by me, and
is only meant to be a mirror for the manifest, which exists in a separate organisation along with the
multiple other repositories needed for building an AOSP project. I'm pretty
well versed with VCS and git, even if I do say so myself.

**Comment by ashwini0529** [comment]
@ATechnoHazard I feel you should check the GitHub documentation first and revise your concepts?
Giving a link to get a better understanding of a fork. I hope it helps.

https://help.github.com/articles/fork-a-repo/#use-someone-elses-project-as-a-starting-point-for-your-own-idea 🙂

**Comment by SphericalKat** [comment]
As I mentioned, I neither created nor named the repository. Take it up with
the people who did.

**Comment by Mehboob16** [comment]
Am here for keks

**Comment by raphielscape** [comment]
In software engineering, a project fork happens when developers take a copy of source code from one software package and start independent development on it, creating a distinct and separate piece of software. The term often implies not merely a development branch, but also a split in the developer community, a form of schism.

**Comment by baalajimaestro** [comment]
Does the person who created this issue have zero knowledge on git? Like wtf dude. You asking @ATechnoHazard to revise git is so saddening. Read that for yourself thx.
